{{- $component := "db" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kbase.fullname" . }}-{{ $component }}
  labels:
    {{- include "kbase.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ $component }}
      {{- include "kbase.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "kbase.fullname" . }}-{{ $component }}
  template:
    metadata:
      {{- with .Values.postgres.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: {{ $component }}
        {{- include "kbase.labels" . | nindent 8 }}
        {{- with .Values.postgres.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.postgres.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-postgres
          securityContext:
            {{- toYaml .Values.postgres.securityContext | nindent 12 }}
          image: "postgres:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
            PGDATA: /var/lib/postgresql/data/pgdata
          {{- with .Values.postgres.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-db-secret
          {{- with .Values.postgres.envFrom}}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - "pg_isready"
            initialDelaySeconds: 30
          readinessProbe:
            exec:
              command:
                - "pg_isready"
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data/
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "kbase.fullname" . }}-{{ $component }}-pvc
