apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
data:
  POSTGRES_DB: "{{ .Values.postgres.settings.postgres_db }}"
  POSTGRES_USER: "{{ .Values.postgres.settings.postgres_user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.settings.postgres_password }}"


