{{- $component := "db" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kbase.fullname" . }}-{{ $component }}
  labels:
    {{- include "kbase.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.web.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/component: {{ $component }}
    {{- include "kbase.selectorLabels" . | nindent 4 }}

