{{- $component := "web" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kbase.fullname" . }}-{{ $component }}
  labels:
    {{- include "kbase.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.web.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.web.service.type "NodePort" }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/component: {{ $component }}
    {{- include "kbase.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.web.service.type "LoadBalancer" }}
  externalTrafficPolicy: Local
  {{- with .Values.web.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}


