imagePullSecrets: []

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

web:
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  django:
    securityContext: {}
    image:
      repository: "ghcr.io/jackwilde/kbase"
      tag: ""
      pullPolicy: Always
    env: []
    envFrom: []
    #  - secretRef:
    #      name: secretName
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi
    settings:
      secret_key: ""
      allowed_hosts: "localhost"
      debug: False
      time_zone: GMT
      csrf_trusted_origins: "http://localhost:8000"
  nginx:
    securityContext: {}
    image:
      tag: "1.27"
      pullPolicy: Always
    env: []
    envFrom: []
    #  - secretRef:
    #      name: secretName
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi
  service:
    annotations: {}
    type: ClusterIP
    port: 80
    loadBalancerSourceRanges: []
    nodePort: ""

postgres:
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  image:
    tag: "17"
    pullPolicy: Always
  env: []
  envFrom: []
  #  - secretRef:
  #      name: secretName
  securityContext: {}
  service:
    annotations: {}
    port: 5432
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  storage:
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: ""
  settings:
    postgres_db: ""
    postgres_user: ""
    postgres_password: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: {}
#    hosts:
#      - chart-example.local
#    secretName: chart-example-tls