apiVersion: v1
entries:
  kbase:
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T16:56:11.040548546Z"
    description: A Helm chart for Kubernetes
    digest: 0267a7d6267f59245db4ba25c7bdb6f7df2ace107eaeda21cb410db920815e6b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.18.tgz
    version: 0.1.18
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T16:56:11.039548448Z"
    description: A Helm chart for Kubernetes
    digest: 448980aa12946c13b40ac996adbd14baf2a6ff2270cd240a510061a8493f422b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.17.tgz
    version: 0.1.17
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2024-11-30T16:56:11.039134049Z"
    description: A Helm chart for Kubernetes
    digest: 5329adf52027811b785c28a31c22f6cf3923020ea0be323348af1d126983139f
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.16.tgz
    version: 0.1.16
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2024-11-30T16:56:11.038736901Z"
    description: A Helm chart for Kubernetes
    digest: b91811df41356d645366dbdee6cb546dde49c77f520a2cd3a66b56c573878702
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.15.tgz
    version: 0.1.15
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2024-11-30T16:56:11.038324565Z"
    description: A Helm chart for Kubernetes
    digest: 469dba6702ec59172f69f9dba62d6b93e893fd8eee343103da183989f3b59cbf
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.14.tgz
    version: 0.1.14
  - apiVersion: v2
    appVersion: 0.0.17
    created: "2024-11-30T16:56:11.037899596Z"
    description: A Helm chart for Kubernetes
    digest: 61e9bded727f76c914a1576bfffb407fd2e8ff929058049d74d761b28fd12969
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.13.tgz
    version: 0.1.13
  - apiVersion: v2
    appVersion: 0.0.13
    created: "2024-11-30T16:56:11.037493632Z"
    description: A Helm chart for Kubernetes
    digest: eb1ba38ad2801ea732622b4f9f3934e2551b6522b69a33ea0511c44408a457c2
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.12.tgz
    version: 0.1.12
  - apiVersion: v2
    appVersion: 0.0.13
    created: "2024-11-30T16:56:11.037092196Z"
    description: A Helm chart for Kubernetes
    digest: 54dfe0506fc6de4751f88c598be538c3d0ea3af328cf39c6ecaef3f867b6ce33
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v2
    appVersion: 0.0.13
    created: "2024-11-30T16:56:11.036689027Z"
    description: A Helm chart for Kubernetes
    digest: 7756650e7fdb9f398a8ab15c90e001be074a1f08fa567194089c187bd315fdc4
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T16:56:11.044134293Z"
    description: A Helm chart for Kubernetes
    digest: c76b2fb7965802cc1a9f8261ec9a83175430710c666e4a613733d59f5849f100
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T16:56:11.043601253Z"
    description: A Helm chart for Kubernetes
    digest: 72e9223c806fe96e7eb68a53b7fc588686c54e0c41406292483e26f4148822d0
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T16:56:11.043210156Z"
    description: A Helm chart for Kubernetes
    digest: 3324820becbbe4d5e57a3a6e1508f22b8baa3b9745c9071e7dc2a52a0350315b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T16:56:11.042815443Z"
    description: A Helm chart for Kubernetes
    digest: b011a603a4b30a1c1a48462567990934c32b3f05744ab1b117023647a0ee666e
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T16:56:11.042421742Z"
    description: A Helm chart for Kubernetes
    digest: 7cdf6d686301b6dc79be0601934da34b3c84b952709e2c428def36cb3e3a5e44
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T16:56:11.041991092Z"
    description: A Helm chart for Kubernetes
    digest: 43230d907d41bf98403f3e17224f16fdfb7e376dbf4d1658dab7ab61e422c5d4
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.0.10
    created: "2024-11-30T16:56:11.041593113Z"
    description: A Helm chart for Kubernetes
    digest: 53cc0d55896b9378e24ddda6263dc78c1eb0fbb6c5045a738351fad9816c8bb7
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.0.10
    created: "2024-11-30T16:56:11.041178132Z"
    description: A Helm chart for Kubernetes
    digest: a63fc516ef96a5f905fed85d465311f0ffb9e548bb323170b2fa26c5feafba28
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.0.10
    created: "2024-11-30T16:56:11.036287291Z"
    description: A Helm chart for Kubernetes
    digest: 28e6b43b6adf406c8d177e126b39db870d558268b31b828469339a8ffdfaec85
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2024-11-30T16:56:11.035835792Z"
    description: A Helm chart for Kubernetes
    digest: 7f1bc5f3c6be37c36b0ea12177c442bfe2f9827c217df4566d623d94550d964a
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-30T16:56:11.035263008Z"
