apiVersion: v1
entries:
  kbase:
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2024-11-30T19:51:10.28108751Z"
    description: A Helm chart for Kubernetes
    digest: cb78d363fda69e7881d5ad76401ddf32ae1ed63ad45b852171ef67c4d1f9579d
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.32.tgz
    version: 0.1.32
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-11-30T19:51:10.280695581Z"
    description: A Helm chart for Kubernetes
    digest: 052bdbd296c4a955ed63c67e40262a93002e7636210df6e6defb8be2d3a31e9d
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.31.tgz
    version: 0.1.31
  - apiVersion: v2
    appVersion: 0.0.22
    created: "2024-11-30T19:51:10.280279095Z"
    description: A Helm chart for Kubernetes
    digest: 56e0d2b1e8fdaab6f1204c60210478df13cd27a08b423c3539cfb5f2ef2387ed
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.30.tgz
    version: 0.1.30
  - apiVersion: v2
    appVersion: 0.0.22
    created: "2024-11-30T19:51:10.279502891Z"
    description: A Helm chart for Kubernetes
    digest: 8f563c9043418eee6a37b036ec3d4518b2ff8c3fcbb80027d3a9bebd759a5c6f
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.29.tgz
    version: 0.1.29
  - apiVersion: v2
    appVersion: 0.0.21
    created: "2024-11-30T19:51:10.279110211Z"
    description: A Helm chart for Kubernetes
    digest: 75b25b2c20923dd80fa6f89a7b6cadd3546b483231a266c3c593101031f27e73
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.28.tgz
    version: 0.1.28
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T19:51:10.278590193Z"
    description: A Helm chart for Kubernetes
    digest: 8731c327bf9a3e99aae01f889522375217f2052218021ba2e7fdf1e96c0a15d8
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.27.tgz
    version: 0.1.27
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T19:51:10.278167596Z"
    description: A Helm chart for Kubernetes
    digest: 367a6c706326ba3f5e342b1adfd7b701c6d708ff53a36cdb1f23abc50ba1a5a0
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.26.tgz
    version: 0.1.26
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T19:51:10.277251303Z"
    description: A Helm chart for Kubernetes
    digest: 73d005797cfb715bd1c4822d07cee9c7344c6301b6884149fd37effa998db9b8
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.25.tgz
    version: 0.1.25
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T19:51:10.27667996Z"
    description: A Helm chart for Kubernetes
    digest: 1425199aab2f7a70969b9046a9d7bd589aed1fcd59b82dac72fa23fea4a3b9bd
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.24.tgz
    version: 0.1.24
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T19:51:10.276259397Z"
    description: A Helm chart for Kubernetes
    digest: 554f600ed900c2146090d915377ab1cf7dd107957738e72da4d6d501facbf33d
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.23.tgz
    version: 0.1.23
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T19:51:10.275881093Z"
    description: A Helm chart for Kubernetes
    digest: 079217cd98c13b93f388e28ddcd1acb991cf0b4bb9cf4272cadd856417869230
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.22.tgz
    version: 0.1.22
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T19:51:10.275480307Z"
    description: A Helm chart for Kubernetes
    digest: 753348ae34d3efe4b52ea39ee396e7549adf6f9bb2c9960e067553d92007af90
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.21.tgz
    version: 0.1.21
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T19:51:10.275065415Z"
    description: A Helm chart for Kubernetes
    digest: 8135fa4b8ffc964b579a6056223c59e36bdc74cb4b70a0ee5449df41b4db551b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.20.tgz
    version: 0.1.20
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T19:51:10.274269053Z"
    description: A Helm chart for Kubernetes
    digest: bcaba59577fd02ccc83b6cc4d821fee4534d2298b1c9d95fa9d8ba7e066d439c
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.19.tgz
    version: 0.1.19
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T19:51:10.273869449Z"
    description: A Helm chart for Kubernetes
    digest: 0267a7d6267f59245db4ba25c7bdb6f7df2ace107eaeda21cb410db920815e6b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.18.tgz
    version: 0.1.18
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T19:51:10.273458765Z"
    description: A Helm chart for Kubernetes
    digest: 448980aa12946c13b40ac996adbd14baf2a6ff2270cd240a510061a8493f422b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.17.tgz
    version: 0.1.17
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2024-11-30T19:51:10.273050485Z"
    description: A Helm chart for Kubernetes
    digest: 5329adf52027811b785c28a31c22f6cf3923020ea0be323348af1d126983139f
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.16.tgz
    version: 0.1.16
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2024-11-30T19:51:10.272638919Z"
    description: A Helm chart for Kubernetes
    digest: b91811df41356d645366dbdee6cb546dde49c77f520a2cd3a66b56c573878702
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.15.tgz
    version: 0.1.15
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2024-11-30T19:51:10.272208117Z"
    description: A Helm chart for Kubernetes
    digest: 469dba6702ec59172f69f9dba62d6b93e893fd8eee343103da183989f3b59cbf
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.14.tgz
    version: 0.1.14
  - apiVersion: v2
    appVersion: 0.0.17
    created: "2024-11-30T19:51:10.271792163Z"
    description: A Helm chart for Kubernetes
    digest: 61e9bded727f76c914a1576bfffb407fd2e8ff929058049d74d761b28fd12969
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.13.tgz
    version: 0.1.13
  - apiVersion: v2
    appVersion: 0.0.13
    created: "2024-11-30T19:51:10.271354839Z"
    description: A Helm chart for Kubernetes
    digest: eb1ba38ad2801ea732622b4f9f3934e2551b6522b69a33ea0511c44408a457c2
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.12.tgz
    version: 0.1.12
  - apiVersion: v2
    appVersion: 0.0.13
    created: "2024-11-30T19:51:10.270428319Z"
    description: A Helm chart for Kubernetes
    digest: 54dfe0506fc6de4751f88c598be538c3d0ea3af328cf39c6ecaef3f867b6ce33
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v2
    appVersion: 0.0.13
    created: "2024-11-30T19:51:10.269356595Z"
    description: A Helm chart for Kubernetes
    digest: 7756650e7fdb9f398a8ab15c90e001be074a1f08fa567194089c187bd315fdc4
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T19:51:10.283425782Z"
    description: A Helm chart for Kubernetes
    digest: c76b2fb7965802cc1a9f8261ec9a83175430710c666e4a613733d59f5849f100
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T19:51:10.283033111Z"
    description: A Helm chart for Kubernetes
    digest: 72e9223c806fe96e7eb68a53b7fc588686c54e0c41406292483e26f4148822d0
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T19:51:10.282641071Z"
    description: A Helm chart for Kubernetes
    digest: 3324820becbbe4d5e57a3a6e1508f22b8baa3b9745c9071e7dc2a52a0350315b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T19:51:10.282250344Z"
    description: A Helm chart for Kubernetes
    digest: b011a603a4b30a1c1a48462567990934c32b3f05744ab1b117023647a0ee666e
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T19:51:10.281862332Z"
    description: A Helm chart for Kubernetes
    digest: 7cdf6d686301b6dc79be0601934da34b3c84b952709e2c428def36cb3e3a5e44
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T19:51:10.281478888Z"
    description: A Helm chart for Kubernetes
    digest: 43230d907d41bf98403f3e17224f16fdfb7e376dbf4d1658dab7ab61e422c5d4
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.0.10
    created: "2024-11-30T19:51:10.279885714Z"
    description: A Helm chart for Kubernetes
    digest: 53cc0d55896b9378e24ddda6263dc78c1eb0fbb6c5045a738351fad9816c8bb7
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.0.10
    created: "2024-11-30T19:51:10.274672724Z"
    description: A Helm chart for Kubernetes
    digest: a63fc516ef96a5f905fed85d465311f0ffb9e548bb323170b2fa26c5feafba28
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.0.10
    created: "2024-11-30T19:51:10.268948355Z"
    description: A Helm chart for Kubernetes
    digest: 28e6b43b6adf406c8d177e126b39db870d558268b31b828469339a8ffdfaec85
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2024-11-30T19:51:10.268482087Z"
    description: A Helm chart for Kubernetes
    digest: 7f1bc5f3c6be37c36b0ea12177c442bfe2f9827c217df4566d623d94550d964a
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-30T19:51:10.267910233Z"
