apiVersion: v1
entries:
  kbase:
  - apiVersion: v2
    appVersion: 0.0.13
    created: "2024-11-30T15:32:35.571008419Z"
    description: A Helm chart for Kubernetes
    digest: 54dfe0506fc6de4751f88c598be538c3d0ea3af328cf39c6ecaef3f867b6ce33
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v2
    appVersion: 0.0.13
    created: "2024-11-30T15:32:35.570345346Z"
    description: A Helm chart for Kubernetes
    digest: 7756650e7fdb9f398a8ab15c90e001be074a1f08fa567194089c187bd315fdc4
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T15:32:35.575064963Z"
    description: A Helm chart for Kubernetes
    digest: c76b2fb7965802cc1a9f8261ec9a83175430710c666e4a613733d59f5849f100
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T15:32:35.574663831Z"
    description: A Helm chart for Kubernetes
    digest: 72e9223c806fe96e7eb68a53b7fc588686c54e0c41406292483e26f4148822d0
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T15:32:35.574250016Z"
    description: A Helm chart for Kubernetes
    digest: 3324820becbbe4d5e57a3a6e1508f22b8baa3b9745c9071e7dc2a52a0350315b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T15:32:35.573845948Z"
    description: A Helm chart for Kubernetes
    digest: b011a603a4b30a1c1a48462567990934c32b3f05744ab1b117023647a0ee666e
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T15:32:35.573438374Z"
    description: A Helm chart for Kubernetes
    digest: 7cdf6d686301b6dc79be0601934da34b3c84b952709e2c428def36cb3e3a5e44
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T15:32:35.573001656Z"
    description: A Helm chart for Kubernetes
    digest: 43230d907d41bf98403f3e17224f16fdfb7e376dbf4d1658dab7ab61e422c5d4
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.0.10
    created: "2024-11-30T15:32:35.572583101Z"
    description: A Helm chart for Kubernetes
    digest: 53cc0d55896b9378e24ddda6263dc78c1eb0fbb6c5045a738351fad9816c8bb7
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.0.10
    created: "2024-11-30T15:32:35.572023773Z"
    description: A Helm chart for Kubernetes
    digest: a63fc516ef96a5f905fed85d465311f0ffb9e548bb323170b2fa26c5feafba28
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.0.10
    created: "2024-11-30T15:32:35.569943493Z"
    description: A Helm chart for Kubernetes
    digest: 28e6b43b6adf406c8d177e126b39db870d558268b31b828469339a8ffdfaec85
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2024-11-30T15:32:35.569494932Z"
    description: A Helm chart for Kubernetes
    digest: 7f1bc5f3c6be37c36b0ea12177c442bfe2f9827c217df4566d623d94550d964a
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-30T15:32:35.568874078Z"
