name: Deploy to Kubernetes
on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Kubernetes Config
        run: |
          CONFIG_FILE=$(mktemp)
          echo "${{ secrets.KUBECONFIG }}" > $CONFIG_FILE
          echo "KUBECONFIG=${CONFIG_FILE}" >> $GITHUB_ENV
      - name: Add Helm repo
        run: |
          helm repo add https://jackwilde.github.io/kbase kbase
          helm repo update
      - name: Deploy with Helm
        run: |
          helm upgrade --install --create-namespace \
            kbase kbase/kbase \
            --namespace kbase
            --dry-run
      - name: Delete Config
        run: rm $CONFIG_FILE
          
