name: Deploy to Kubernetes
on:
  workflow_dispatch: {}

env:
  KUBECONFIG: "${{ secrets.KUBECONFIG }}"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Kubernetes Config
        run: |
          kubectl config view
          
