name: Deploy to Kubernetes
on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Kubernetes Config
        run: |
          CONFIG_FILE=$(mktemp)
          tee $CONFIG_FILE <<< "${{ secrets.KUBECONFIG }}"
          echo "KUBECONFIG=${CONFIG_FILE}" >> $GITHUB_ENV
      - name: Test Config
        run: |
          kubectl get pods 
          
