name: Publish Helm chart

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - '.github/workflows/publish-chart.yml'

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Package Chart
        working-directory: helm/kbase
        run: |
          helm package .
          helm repo index ${{ steps.deployment.outputs.page_url }} .
          cat index.html
          
          
