name: Publish Helm chart

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - '.github/workflows/publish-chart.yml'

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set URL
        run: |
          REPO_NAME=$( awk -F '/' '{print$NF}' <<< ${GITHUB_REPOSITORY})
          echo "URL=https://${GITHUB_REPOSITORY_OWNER}/github.io/${REPO_NAME}" >> $GITHUB_ENV
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Package Chart
        working-directory: helm/kbase
        run: |
          helm package .
          echo ${{ env.URL }}
          helm repo index --url ${{ env.URL }} .
          cat index.yaml
